apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://app.getambassador.io/yaml/emissary/2.2.2/emissary-crds.yaml
- https://app.getambassador.io/yaml/emissary/2.2.2/emissary-emissaryns.yaml
