apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: poc-
commonLabels:
  environment: poc

resources:
- ../../base
- https://app.getambassador.io/yaml/emissary/2.2.1/emissary-emissaryns.yaml
