apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: poc-
commonLabels:
  environment: poc

resources:
- ../../base

patches:
- path: patch-service-argocd-server.yaml
  target:
    kind: Service
    labelSelector: app.kubernetes.io/name=argocd-server
